In [1]:
#NumPy is a general-purpose array-processing package. 
#It provides a high-performance multidimensional array object
#It is the fundamental package for scientific computing with Python. 

In [3]:
# Creating Arrays

import numpy as np

arr = [1,2,3,4,5]
arr = np.array(arr)
print(arr)

array([1, 2, 3, 4, 5])

In [7]:
# 2-D array

arr = np.array([[10,20,30],[40,50,60]])
print(arr)

# Print shape
print(arr.shape)

# Print length
print(len(arr))

# Print datatype
print(arr.dtype)


[[10 20 30]
 [40 50 60]]
(2, 3)
2
int32


In [12]:
# Functions to Create Arrays:

arr= np.zeros(3)
print(arr)

# Print datatype
print(arr.dtype)


[0. 0. 0.]
float64


In [13]:
arr = np.ones([5,5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
# Numpy Maths

y = np.array([[1,2], [4,5]])
x = np.array([[9,8],[7,6]])
             
print(np.add(x,y))

print('*'*10)
             
print(np.subtract(x,y))

print('*'*10)
             
print(np.multiply(x,y)) 

print('*'*10)
             
print(np.divide(x,y)) 

[[10 10]
 [11 11]]
**********
[[8 6]
 [3 1]]
**********
[[ 9 16]
 [28 30]]
**********
[[9.   4.  ]
 [1.75 1.2 ]]


In [30]:
# Array Indexing

arr = np.arange(8)
print(arr)
arr[5]

[0 1 2 3 4 5 6 7]


5

In [31]:
arr[1:4]

array([1, 2, 3])

In [32]:
arr[1:4] = 100
arr

array([  0, 100, 100, 100,   4,   5,   6,   7])

In [37]:
# Array Slicing

arr = np.arange(8)
print(arr)

print(arr[:3])

print(arr[2:6])

#Reversing an array
print(arr[::-1])


[0 1 2 3 4 5 6 7]
[0 1 2]
[2 3 4 5]
[7 6 5 4 3 2 1 0]


In [46]:
arr = np.array([[5,10,15],[20,25,30],[30,35,40]])
print(arr)

print('*'*10)

print(arr[1])

print('*'*10)

print(arr[1][0])

print('*'*10)

print(arr[:2,1:])

[[ 5 10 15]
 [20 25 30]
 [30 35 40]]
**********
[20 25 30]
**********
20
**********
[[10 15]
 [25 30]]


In [49]:
#array Transposition

arr = np.arange(18).reshape(6,3)
print(arr)

print('*'*30)

arr.T


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
******************************


array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [51]:
#Dot product of Arrays

x = np.arange(5)
y = np.arange(5,10)
print(x)
print(y)

print('*'*10)

print(np.dot(x,y))


[0 1 2 3 4]
[5 6 7 8 9]
**********
80


In [72]:
# Universal Array Functions and Stats

A = np.arange(5,11)
print(A)
np.sqrt(A)

[ 5  6  7  8  9 10]


array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [73]:
np.exp(arr)

array([0.4610657 , 0.10390409, 3.46811733, 1.25860992, 8.48828578,
       0.93426782, 0.71467194, 3.37922027, 0.34314775, 2.28730211])

In [74]:
B = arr = np.random.randn(10)
print(B)

[-2.49265468 -2.58201846  1.62795331  0.9835926   1.96773531  2.33985847
  0.47376733  0.06021966  0.05229198  1.03861685]


In [75]:
C = arr = np.random.randn(10)
print(C)

[ 1.22396969  1.04164937 -1.40828088  0.79058351 -1.20808249  1.24650851
  0.54941304  0.00344632 -1.20369791  1.51247487]


In [76]:
np.maximum(B,C)

array([1.22396969, 1.04164937, 1.62795331, 0.9835926 , 1.96773531,
       2.33985847, 0.54941304, 0.06021966, 0.05229198, 1.51247487])

In [80]:
A = np.array([10,15,20,25,30,35])
np.mean(A)

22.5

In [81]:
B = np.array([22,33,44,55,66,77])
np.std(B)

18.786076404259266

In [82]:
C = np.array([20,40,60,80,100,120])
np.median(C)

70.0